export type IPersona = {
  persona_id: string;
  name: string;
  category_name: null;
  agent_category: string;
  agent_intended_age: string;
  fe_system_prompt: string | null;
  end_user_age_considertion: boolean;
  fe_strict_knowledge_prompt: string | null;
  fe_knowledge_base: string;
  fe_assistant_prompt: string | null;
  knowladge_base: string;
  chat_date_time: string;
  system_prompt: string;
  assistant_prompt: string;
  strict_knowledge_prompt: string;
  personality_system_prompt: string;
  personality_system_prompt_2: string;
  personality_system_prompt_3: string;
  vision_enabled: boolean;
  vision_model: string;
  vision_prompt: string;
  audience_type: string;
  personality: string;
  randomize_personality: boolean;
  do_not_say: string;
  personality_setup_settings: string;
  msg_history_count: number;
  conversational_outputresponse_type: string;
  include_usersname_in_convo: boolean;
  consider_users_age: boolean;
  user_memory: boolean;
  user_memory_msg_batch: number;
  voice_id: string;
  setup_voice_engine: string;
  quota: number;
  quota_time_frame: number;
  auto_message_time: number;
  auto_msg_prompt: string;
  enable_auto_messaging: boolean;
  voice_response_percentage: string | number;
  subscription_only: boolean;
  subscription_price: string;
  subscription_quota: number;
  subscription_price_id: string;
  buy_product_link: string;
  buy_product_price: string;
  deposit_price: string;
  deposit_quota: number;
  expired_quota_text_non_subscribed: string;
  expired_quota_text: string;
  deposit_price_id: string;
  deposit_provider: string;
  teleg_checkout_test_key: string;
  teleg_checkout_prod_key: string;
  teleg_checkout_test_mode: boolean;
  out_of_credit_reply: string;
  agent_suggested_questions: string;
  subscribe_text: string;
  deposit_text: string;
  deposit_text_non_subscribed: string;
  wa_number_token: string;
  whatsapp_number: string | null;
  whatsapp_business_account_id: string | null;
  whatsapp_secret_key: string | null;
  whatsapp_active: boolean;
  teleg_token: string | null;
  telegram_active: boolean;
  telegram_username: string | null;
  is_premium: boolean;
  knowladge_strict: boolean;
  llm_only: boolean;
  debug_mode: boolean;
  knowladge_base_id: string | null;
  knowladge_base_version: string;
  onboarding_start_statment: string;
  system_agentintel: string;
  onboarding_name_question: string;
  onboarding_gender_question: string;
  onboarding_country_question: string;
  onboarding_state_question: null;
  onboarding_dob_question: string;
  onboarding_email_question: string;
  onboarding_self_describe_question: string;
  coupon_code_question: null;
  onboarding_close_statment: string;
  hello_text: string;
  latest_text: string;
  welcome_message: string;
  welcome_image: string;
  profile_image: string;
  profile_about: string;
  profile_address: string;
  profile_description: string;
  profile_email: string | null;
  profile_website: string | null;
  help_domain: string;
  agent_suggested_question1: string;
  agent_suggested_question2: string;
  agent_suggested_question3: string;
  agent_suggested_question4: string;
  agent_suggested_question5: string;
  agent_suggested_question6: string;
  model: string;
  temperature: number;
  max_tokens: number;
  buffer_messages: boolean;
  buffer_time: number;
  max_users: number;
  is_active: boolean;
  owner: string;
  unique_id: string;
  date_created: string;
  customize_character: boolean;
  is_template?: boolean;
  nationality: string;
  monetize: boolean;
  affiliates_enable: boolean;
  agent_role: string;
  creator_notes_activate: boolean;
  creator_notes: string;
};

export type IUserConvos = {
  id: string | number;
  user_id: string | number;
  persona_id: string | number;
  subscription_id: string;
  quota: number;
  is_active: boolean;
  is_premium: boolean;
  is_subscribed: boolean;
  religion_status: string;
  relation_status: string;
  political_status: string;
  religion_score: number;
  relation_score: number;
  political_score: number;
  active_setting: null; //temporary
  language: string;
  last_reset: string;
  in_waiting_room: boolean;
  in_auto_msg_queue: boolean;
  planned_msg: string;
  timestamp: string;
};
